FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./ 
RUN npm install
RUN npm install --save-dev @types/express @types/node cors @types/cors

COPY . .

RUN npm run build

EXPOSE 3001

CMD ["node", "dist/index.js"]
